name: AI-SCA-Security-Scan

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ai-sca-fix:
    runs-on: ubuntu-latest

    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GIT_PAT: ${{ secrets.GIT_PAT }}
      GIT_COMMITTER_NAME: GitHub Actions Bot
      GIT_COMMITTER_EMAIL: actions@github.com

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python Requirements
        run: pip install -r requirements.txt

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run SCA Scan
        run: ./scripts/scan-sca.sh

      - name: Run OpenAI Helper
        run: python3 utils/openai_helper.py

      - name: AI Fix Vulnerabilities
        run: python3 ai_fix_agent.py

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GIT_PAT }}@github.com/Yush1902/ai-sca.git

      - name: Commit & Push Fixed
        run: python3 scripts/git_ops.py

